### ISSUE TITLE
Plans for editions

### ISSUE THREAD

**Issue by vorner** [rust-lang-nursery/nomicon#100]
Hello

I've started to edit the lifetimes chapter because NLL is coming with the 2018 edition and there are some differences (and some „should not compile“ examples actually compile under that edition). Then I noticed that even nightly still doesn't use NLL on the 2015 edition and my new examples fail the `mdbook test` (and I haven't found a way to enable the 2018 edition in mdbook).

My question is what should nomicon do about editions. Should it mostly aim for the latest one and optionally point out differences to previous editions? Should it start getting „ported“ as soon as possible? If so, what about the failing examples? Or should I postpone the migration and just make sure that one example (https://doc.rust-lang.org/nightly/nomicon/lifetime-mismatch.html) successfully fails to compile?

**Comment by steveklabnik** [comment]
In general, most documentation focuses on just the “latest” edition, and I’d think that applies to the nomicon too.

That said, I can also see it having a 2015 section...

**Comment by Gankro** [comment]
yeah as a matter of policy, the nomicon tries to stick to the present, with references to versions when it's a potentially volatile issue (e.g. "as of rust x.y.z, ..."). Old versions are always available for the interested reader.

**Comment by Gankro** [comment]
As for migration, we can always land the examples as `ignore` as a transitional measure.

**Comment by RalfJung** [comment]
According to https://github.com/rust-lang/rust/blob/master/src/doc/rustdoc/src/documentation-tests.md, you can use ```` ```edition2018 ```` to make your doctest compile with the new edition.

**Comment by vorner** [comment]
Thank you, yes, I was already pointed to that direction :-). I must have been reading the stable-rustdoc documentation.

It is working for me now (I'll see if it actually passes CI once I submit the PR).

I guess this can be closed, then.
