### ISSUE TITLE
Is 0 alloc UB?

### ISSUE THREAD

**Issue by nico-abram** [rust-lang-nursery/nomicon#120]
I've been playing with 0 allocs (After reading https://doc.rust-lang.org/stable/nomicon/exotic-sizes.html#zero-sized-types-zsts I was expecting it to give me null pointers) but I kept getting seg faults. Asking in the rust discord, someone told me 0 allocs are UB (And they only *may* return null pointers). If so, I think clarifying that they're UB a bit more might be a good idea.

I'm having a great time reading the book by the way, great job :+1:

**Comment by RalfJung** [comment]
> Is 0 alloc UB?

Yes, allocations of size 0 are UB.

**Comment by Gankro** [comment]
This is strictly speaking documented here: https://doc.rust-lang.org/nomicon/vec-zsts.html

And is documented on the actual allocator APIs: https://doc.rust-lang.org/alloc/alloc/trait.GlobalAlloc.html#safety

It's not within the scope of the nomicon to document all UB in all random library methods, so I think we're doing a fine job already.
