### ISSUE TITLE
"Probably" typo

### ISSUE THREAD

**Issue by kylejlin** [rust-lang-nursery/nomicon#137]
**Expected (correction bolded):**

> As an aside, while `Send` and `Sync` are unsafe traits, they are also automatically implemented for types when such derivations are pro**b**ably safe to do.

**Actual (typo bolded):**

> As an aside, while `Send` and `Sync` are unsafe traits, they are also automatically implemented for types when such derivations are pro**v**ably safe to do.

Fixed by #136

**Comment by Lokathor** [comment]
There is no typo here, this issue can be closed.
