### ISSUE TITLE
Nomicon doesn't mention that dereferencing an unaligned pointer is UB

### ISSUE THREAD

**Issue by jimblandy** [rust-lang-nursery/nomicon#15]
The Nomicon and the Reference don't say that dereferencing a misaligned pointer is undefined behavior, but I certainly would expect it to be. Checked with @gankro on IRC and he agreed.

To verify, I compiled the following:

extern {
    fn f() -> *const i32;
}

fn main() {
    println!("{}", unsafe { *f() + 1 });
}

This produces LLVM IR containing the following code for the call:

  %3 = tail call i32* @f()
  %4 = load i32, i32* %3, align 4
  %5 = add i32 %4, 1

The align 4 in the load instruction indicates that LLVM should assume that the pointer is aligned on a four-byte boundary. The LLVM IR docs for load say, "Overestimating the alignment results in undefined behavior."

See also: https://github.com/rust-lang-nursery/reference/issues/49

**Comment by vorner** [comment]
I think it mentions so now, in `what-unsafe-does`. This is from current master:

> Unlike C, Undefined Behavior is pretty limited in scope in Rust. All the core
> language cares about is preventing the following things:
>
> * Dereferencing null, dangling, or *unaligned* pointers

However, I think the list is still not complete. Is every bit pattern a valid `f32` or `f64`? Furthermore, I think mutating an aliased location is also considered UB (unless that location is inside an `UnsafeCell`, that is).

**Comment by Gankro** [comment]
Floats have no undefined patterns.

Mutating stuff is, broadly, covered by "pointer aliasing"

**Comment by Gankro** [comment]
Seems we're good here?

**Comment by vorner** [comment]
Sorry, I wasn't paying enough attention when reading. Yes, I see it there now, thank you.
