### ISSUE TITLE
Recommend MaybeUninit now that it's stable

### ISSUE THREAD

**Issue by est31** [rust-lang-nursery/nomicon#150]
The nomicon still recommends `mem::uninitialized` in the "Unchecked Uninitialized Memory" section.

**Comment by est31** [comment]
cc @RalfJung @steveklabnik

**Comment by RalfJung** [comment]
Cc @Gankro this basically needs incorporating your blog post :)

**Comment by RalfJung** [comment]
I submitted a PR at https://github.com/rust-lang-nursery/nomicon/pull/153.
