### ISSUE TITLE
repr(Rust) page includes a list item where it shouldn't

### ISSUE THREAD

**Issue by brennie** [rust-lang-nursery/nomicon#20]
The published nomicon renders the following

```markdown
Alignment is at least 1, and always a power of
2. Most primitives are generally aligned to their size, although this is platform-specific behavior. In particular, on x86 u64 and f64 may be only aligned to 32 bits.
```

as

---
Alignment is at least 1, and always a power of

2. Most primitives are generally aligned to their size, although this is platform-specific behavior. In particular, on x86 u64 and f64 may be only aligned to 32 bits.
---
which can be seen [here](https://doc.rust-lang.org/nomicon/repr-rust.html).

I think this is a bug in `mdbook`.

**Comment by steveklabnik** [comment]
It's not; it's a difference between CommonMark and hoedown. We need to change the text slightly.

**Comment by Lokathor** [comment]
This has been fixed by now, and the issue can be closed.
