### ISSUE TITLE
mdbook test failing for destructors.md and vec-final.md

### ISSUE THREAD

**Issue by projektir** [rust-lang-nursery/nomicon#22]
destructors.md has a bunch of failing `as_ptr` calls; vec-final.md has that as well as `Unique::empty`. Seems like those don't exist anymore.

**Comment by steveklabnik** [comment]
Hm, weird, since Travis is passing....

**Comment by steveklabnik** [comment]
okay so https://travis-ci.org/rust-lang-nursery/nomicon/builds/228937974 was failing, but https://travis-ci.org/rust-lang-nursery/nomicon/builds/233662610 is passing. Dunno, but looks like it's green again.

**Comment by steveklabnik** [comment]
Apparently this is still failing for @projektir locally

**Comment by projektir** [comment]
Looks like the nomicon is just more up to date than I am, issue cleared up after I updated to latest nightly.

**Comment by steveklabnik** [comment]
@projektir had an old nightly; closing!
