### ISSUE TITLE
repr(C) vs drop flags confusion

### ISSUE THREAD

**Issue by vojtechkral** [rust-lang-nursery/nomicon#37]
Hi,
  the [chapter on `repr(C)`](https://doc.rust-lang.org/nightly/nomicon/other-reprs.html) says:

> If the type would have any drop flags, they will still be added

but the chapter on [drop flags](https://doc.rust-lang.org/nomicon/drop-flags.html) says:

> The drop flags are tracked on the stack and no longer stashed in types that implement drop.

Is the remark in the section on `repr(C)` outdated? (Or am I maybe missing something?)

Thanks!

**Comment by sfackler** [comment]
The repr(C) section is outdated - drop flags are no longer attached to types.

**Comment by vojtechkral** [comment]
@sfackler Ok, thanks. Mind if I just create a PR removing that point?

**Comment by sfackler** [comment]
Go for it!
