### ISSUE TITLE
Exotically Sized Types page has out-of-date note about misaligned DST fields

### ISSUE THREAD

**Issue by alercah** [rust-lang-nursery/nomicon#52]
https://doc.rust-lang.org/nomicon/exotic-sizes.html says that DSTs are broken when the last field has a variable position based on alignment, but that bug has been fixed.

**Comment by Gankro** [comment]
This is fixed on nightly, but thanks for reporting it!

**Comment by Gankro** [comment]
https://doc.rust-lang.org/nightly/nomicon/exotic-sizes.html <-- in case you didn't know how to check out the freshest docs in the galaxy
