### ISSUE TITLE
Clarify FFI-safety of Option<extern "C" fn>

### ISSUE THREAD

**Issue by ramosbugs** [rust-lang-nursery/nomicon#59]
Relatively new to Rust, and reading through the Nomicon to make sure I build a new FFI module safely. I noticed one omission in https://github.com/rust-lang-nursery/nomicon/blob/master/src/other-reprs.md.

#13 added language to call out that `Option<&T>` is FFI-safe as long as `*const T` is FFI-safe. Based on https://github.com/rust-lang/rust/issues/40913, it seems that the preferred way of expressing nullable function pointers (returned via FFI) is using `Option<fn>` (or I guess `Option<extern "C" fn>` since function pointers set by C code are presumably also C-ABI).

If my understanding is correct, shall we add this to the Nomicon? I'm happy to send a PR if that's desired.

Also, are `Option<&T>` and `Option<extern "C" fn>` an exhaustive list of `repr(C)` FFI-safe enums with fields, or are there other exceptions to document as well?

**Comment by ramosbugs** [comment]
Actually, it looks like this is covered by the [nullable pointer optimization section](https://doc.rust-lang.org/nomicon/ffi.html#the-nullable-pointer-optimization), which specifically mentions function pointers (along with `&T`, `&mut T`, and boxes). I wonder if it's worth including a forward pointer to the more comprehensive section in the bullet added in #13 (cc: @geofft).

**Comment by Gankro** [comment]
Being more clear shouldn't hurt here.

**Comment by Gankro** [comment]
If possible the clarified language on other-reprs should link to the nullable pointer optimization. I'm thinking the wording should be something like:

> If `T` is an FFI-safe non-nullable pointer type, `Option<T>` is guaranteed to have the same layout/ABI as `T` and is therefore also FFI-safe. As of this writing, this covers `&`, `&mut`, and function pointers.
