### ISSUE TITLE
Table partially shown and unscrollable on mobile phones

### ISSUE THREAD

**Issue by lilydjwg** [rust-lang-nursery/nomicon#69]
The [PhantomData](https://doc.rust-lang.org/nomicon/phantom-data.html) page contains a table of three columns. I can see only the first two columns on my phone, and it isn't scrollable.

**Comment by Lokathor** [comment]
On my own phone, the current build of the page can be scrolled horizontally to see the whole table.

@lilydjwg can you please re-check the page in question?

**Comment by lilydjwg** [comment]
Yes, it scrolls fine now.
