### ISSUE TITLE
"mdbook test" fails immediately: No such file or directory

### ISSUE THREAD

**Issue by RalfJung** [rust-lang-nursery/nomicon#78]
I installed mdbook and then ran `mdbook test` as described in the README, but all that does is
```
2018-07-16 13:03:07 [ERROR] (mdbook::utils): Error: Unable to open the file
2018-07-16 13:03:07 [ERROR] (mdbook::utils): 	Caused By: No such file or directory (os error 2)
```

**Comment by RalfJung** [comment]
Judging from the `strace` output, it seems confused by the lack of an index.md?

**Comment by RalfJung** [comment]
mdBook 1.8 got released the day CI started failing, so I guess that's what broke it.

Cc @Michael-F-Bryan

**Comment by RalfJung** [comment]
This actually seems to be a bug in mdBook because the update claims to be semver-compatible, but as this examples shows, it is not.

**Comment by Gankro** [comment]
cc @steveklabnik

**Comment by Lokathor** [comment]
As of `v0.2.3` or later this seems to be fixed. I was able to `mdbook build` and then `mdbook test`.

We can probably close this one.
